sudo: false
language: python
python:
  - '2.7'
  - '3.3'
  - '3.4'
env:
  global:
    - DB=postgres
  matrix:
    - DJANGO=1.6.5
    - DJANGO=1.7.4
install:
  - pip install psycopg2 flake8 nose>=1.3.0 django-nose>=1.3 coverage coveralls Django==$DJANGO
  - pip install -r requirements/docs.txt
before_script:
  - psql -c 'CREATE DATABASE dynamic_db_router_one;' -U postgres
  - psql -c 'CREATE DATABASE dynamic_db_router_two;' -U postgres
script:
  - flake8 .
  - coverage run --branch --source=dynamic_db_router manage.py test
  - coverage report --fail-under=100
  - python setup.py install
  - cd docs && make html
  - pip freeze
after_success:
  coveralls
